runtime: python27
api_version: 1
threadsafe: true
skip_files:
- .git/
- .gitingore
- node_modules/
- css/
- fonts/
- img/
- js/
- snd/
- index.html
- dev-app.yaml
- package.json
- package-lock.json
- README.md

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /about
  static_files: dist/about.html
  upload: dist/about.html

- url: /favicon.ico
  static_files: dist/favicon.ico
  upload: dist/favicon.ico

- url: /index(.*)
  static_files: dist/index.html
  upload: dist/index.html

- url: /css/(.*)
  static_files: dist/css/\1
  upload: dist/css/(.*)

- url: /fonts/(.*)
  static_files: dist/fonts/\1
  upload: dist/fonts/(.*)

- url: /img/(.*)
  static_files: dist/img/\1
  upload: dist/img/(.*)

- url: /snd/(.*)
  static_files: dist/snd/\1
  upload: dist/snd/(.*)

- url: /js/(.*)
  static_files: dist/js/\1
  upload: dist/js/(.*)

- url: /api/servers.*
  script: api.servers.app
